# Generated by Django 3.1.1 on 2020-09-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0002_draco_profile_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_line', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('job', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='draco_profile',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_works', to='profile_cv.work_experiences'),
        ),
    ]
