# Generated by Django 3.1.1 on 2020-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0003_auto_20200928_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experiences',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
