# Generated by Django 3.1.1 on 2020-09-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0004_work_experiences_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draco_profile',
            name='work',
        ),
        migrations.AddField(
            model_name='draco_profile',
            name='works',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_works', to='profile_cv.Work_Experiences'),
        ),
    ]
