# Generated by Django 3.1.1 on 2020-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0006_auto_20200928_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award_Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_line', models.CharField(max_length=250)),
                ('des', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='draco_profile',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='my_award', to='profile_cv.Award_Achievements'),
        ),
    ]
