# Generated by Django 3.1.1 on 2020-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0007_auto_20200929_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draco_profile',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='my_works', to='profile_cv.Work_Experiences'),
        ),
    ]
