# Generated by Django 3.1.1 on 2020-09-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0009_auto_20200929_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technical_skills',
            old_name='technical',
            new_name='category',
        ),
    ]
